export default {
  bemVindo: "Welcome!",
  homeDescricaoBanner: "Our work is make your life more easier",
  BotaoVerFerramentas: "See Tools",
  formatador: "Formatter",
  fotoFormatadorAlt:
    "Formatter HTML, CSS, Javascript, Vue, XML, PHP, JSON, YAML, MarkDown",
  ferramentas: "Tools",
  listaFerramentasDescricao:
    "List of available tools, needing something specific? contact us by chat.",
  listaFerramentasDescricao2: "Found some",
  bug: "bug",
  infomeChat: "inform by chat, that we will fix it immediately.",
  utilidadesTexto: "Text Utilities",
  formatadoresCompactadores: "Formatters and Compactors",
  codificadoresDecodificadores: "Encoders and Decoders",
  geradores: "Generators",
  converterTextoMaiusculo: "Convert text to uppercase",
  converterTextoMinusculo: "Convert text to lowercase",
  converterTextoAlternado: "Convert text to Alternate",
  primeiraLetraMaiusculo: "First Letter in Capital",
  primeiraLetraCadaPalavraMaiusculo: "First Letter of Each Word in Uppercase",
  textoRasurado: "Text S̶t̶r̶i̶k̶e̶t̶h̶r̶o̶u̶g̶h̶",
  textoSimboloBarra: "Text B̷a̷r̷ ̷S̷y̷m̷b̷o̷l̷",
  textoSublinhado: "Text u͟n͟d͟e͟r͟l͟i͟n͟e͟d͟",
  textoSublinhadoDuplo: "Text d͇o͇u͇b͇l͇e͇ ͇u͇n͇d͇e͇r͇l͇i͇n͇e͇",
  textoSublinhadoPontilhada: "Text D̤o̤t̤t̤e̤d̤ ̤l̤i̤n̤e̤",
  textoSublinhadoOnda: "Text w̤a̤v̤e̤ ̤l̤i̤n̤e̤",
  textoEspelhado: "Text Mirrored",
  onlineNotepad: "Notepad Online",
  textoEspacado: "Test Spaced",
  editorHtml: "Live Online HTML Editor",
  codificarDecodificar: "Encode or Decode",
  geradorLorem: "Loren Ipsum Generator ",
  ajudeManterSite: "Help keep this site online",
  footerText:
    "This platform is intended to help people, providing tools to facilitate everyday day.",
  footerText2:
    "If you have any questions or suggestions, do not hesitate to call us.",
  conversorTextos: "Text Converter",
  conversorTextosDescricao: "Convert your text with this simple tool.",
  informarBugTexto:
    "This tool has been tested and is working, if you discover a",
  informarBugTexto2: ", please report it via chat.",
  sugestaoTexto:
    "Do you have any suggestions? inform by chat, if it is interesting, we put the link of your portfolio in the footer for 1 week.",
  obrigadoUtilizarTexto: "Thank you for using our tool! ",
  botaoPrimeiraLetraTodosMaiusculo: "1º letter of all capital",
  botaoPrimeiraLetraMaiusculo: "1º capital letter",
  maiusculo: "capital",
  minusculo: "tiny",
  alternando: "alternating",
  vamosCorrigir: "Let's fix?",
  geradorTextoTachado: "Strikethrough online text generator",
  geradorTextoTachadoDescricao:
    "Generate modified texts using this simple tool.",
  usadoFacebookWhatsapp: "The generated texts can be pasted into the",
  usadoFacebookWhatsapp2: "Facebook, Instagram, Twitter, WhatsApp",
  usadoFacebookWhatsapp3: "and other social networks.",
  botaoRasurado: "S̶t̶r̶i̶k̶e̶t̶h̶r̶o̶u̶g̶h̶",
  botaoSimbiloBarra: "B̷a̷r̷ ̷S̷y̷m̷b̷o̷l̷",
  botaoSublinhado: "u͟n͟d͟e͟r͟l͟i͟n͟e͟d͟",
  botaoSublinhadoDuplo: "d͇o͇u͇b͇l͇e͇ ͇u͇n͇d͇e͇r͇l͇i͇n͇e͇",
  botaoLinhaPontilhada: "D̤o̤t̤t̤e̤d̤ ̤l̤i̤n̤e̤",
  botaoLinhaOnda: "w̤a̤v̤e̤ ̤l̤i̤n̤e̤",
  qualTexto: "what is the text?",
  qualCodigo: "what is the code?",
  resultadoApareceraAqui: "The result will appear here",
  copiar: "copy",
  limpar: "clear",
  fechar: "close",
  copiado: "Copied!",
  colar: "paste",
  frases: "Phrases",
  formatar: "Format",
  gerar: "generate",
  idioma: "language",
  idiomas: "languages",
  portugues: "Portuguese",
  ingles: "English",
  quantidade: "Quantity",
  paragrafosPalavras: "Paragraphs or Words",
  paragrafos: "Paragraphs",
  palavras: "Words",
  numeros: "numbers",
  numero: "Number",
  letra: "Word",
  codigoMorse: "Morse code",
  simbolo: "Symbol",
  espacoBranco: "*Blank space",
  padrao: "default",
  outros: "others",
  opcoes: "options",
  acessar: "access",
  ouveErroCopiar:
    "There was an error copying, do you think it is a bug? inform by chat",
  crieTextoEspelhado: "Create your mirrored text Online",
  crieTextoEspelhadoDescicao:
    "Create your mirrored text with this simple tool.",
  crieTextoEspacado: "Create your text Spaced Online",
  crieTextoEspacadoDescicao: "Create your Spaced text with this simple tool.",
  tamanhoEspacoLetras: "Size of the space between the letters.",
  notepadOnline: "Notepad Online",
  notepadOnlineDescricao: "Write your content with this simple tool.",
  escrevaAlgoIncrivel: "Write something amazing!",
  editorHtmlTitulo: "Online HTML Editor",
  editorHtmlDescricao: "Write your HTML with this simple tool.",
  programeAlgoIncrivel: "Program something amazing!",
  formatadorOnline: "Format Code Online",
  formatadorOnlineDescricao: "Keep your code organized with this simple tool.",
  obrigadoBomCode: "Thank you! and good code!",
  coleCodigoIncrivel: "Paste your amazing code here!",
  erroFormatar:
    "There was an error when formatting, did you choose the right language? Report the error by chat",
  formatarJson5: "Format as JSON5",
  formatarStringfy: "Format as Json Stringify",
  codeEditorTexto:
    "<p>Hello World!</p> \n\n<h1>Paste your awesome code here!</h1>",
  codificadorDecodificadorUrl: "Url Encoder / Decoder",
  codificadorDecodificadorUrlDescricao:
    "Decode your URL with this simple tool.",
  codificador: "Encoder",
  decodificador: "Decoder",
  codificadorDecodificadorBase64: "Base64 Online Encoder / Decoder",
  codificadorDecodificadorBase64Descricao:
    "Manage your Base64 with this simple tool.",
  codificadorDecodificadorCodigoMorse: "Online Morse Code Encoder / Decoder",
  codificadorDecodificadorCodigoMorseDescricao:
    "Encode or Decode your Morse Code with this simple tool.",
  tabelaCodigoMorse: "Morse Code Table",
  codificadorDecodificadorCodigoBinario: "Online Binary Code Encoder / Decoder",
  codificadorDecodificadorCodigoBinarioDescricao:
    "Encode or Decode your Binary Code with this simple tool.",
  geradorLorenOnline: "Online Loren Ipsum Generator",
  geradorLorenOnlineDescricao:
    "Generate Lorem Ipsum text with this simple tool.",
  paginaInicial: "Online Tools",
  paginaInicialDescricao:
    "Online tools to make your life easier. We have Converters, Texts for WhatsApp, HTML Formatters, JS, and much more, Access!",
  codificadorBase64: "Base64 Online Encoder and Decoder",
  codificadorBase64Descricao:
    "Base64 decoder and encoder online with live changes! we have several tools to make your life easier! Access!",
  codificadorBinario: "Online Binary Code Encoder and Decoder",
  codificadorBinarioDescricao:
    "Online Binary Code Encoder and Decoder with live changes! We have several tools to make your life easier!",
  codificadorUrl: "Online URL Encoder and Decoder",
  codificadorUrlDescricao:
    "Decoder and URL encoder online with live changes! we have several tools to make your life easier! Access!",
  conversorTextosTitle: "Online Text to Uppercase Converter, and much more!",
  conversorTextosTitleDescricao:
    "Online text converter, we have uppercase to lowercase, changing, first letter of all uppercase and first letter capitalized.",
  conversorCsv: "Online CSV to HTML Converter",
  conversorCsvDescricao:
    "Convert your csv file to html online quickly! we have several tools to make your life easier! Access!",
  editorHtmlTitle: "Online HTML Editor",
  editorHtmlTitleDescricao:
    "Edit your HTML online with live change! we have several tools to make your life easier! Access!",
  conversorNotepad: "Notepad Online",
  conversorNotepadDescricao:
    "Create your text easily with Notepad online! we have several tools to make your life easier! Access!",
  formatadorCodigos: "Online Code Formatter",
  formatadorCodigosDescricao:
    "Format your html, css, javascript, json, php, vue, angular, less, among others online easily! Access.",
  geradorLoren: "Loren Ipsum Online Generator",
  geradorLorenDescricao: "Lorem Ipsum Online Generator",
  textoEspelhadoTitle: "Create your Mirror Text Online",
  textoEspelhadoDescricao:
    "Create your live mirrored Text! paste on WhatsApp, Facebook, Instagram, Twitter, we have several tools to make your life easier! Access!",
  tradutorMorse: "Online Morse Code Encoder and Decoder",
  tradutorMorseDescricao:
    "Online Morse Code Encoder and Decoder with live changes! We have several tools to make your life easier!",
  textoEspacadoTitle: "Create your text Spaced Online",
  textoEspacadoDescricao:
    "Create your Spaced Text live! paste on WhatsApp, Facebook, Instagram, Twitter, we have several tools to make your life easier! Access!",
  textoTachado: "Create your Strikethrough Text Online",
  textoTachadoDescricao:
    "Create your text with B̷a̷r̷, S̶t̶r̶i̶k̶e̶t̶h̶r̶o̶u̶g̶h̶, u͟n͟d͟e͟r͟l͟i͟n͟e͟d͟, d͇o͇u͇b͇l͇e͇ ͇u͇n͇d͇e͇r͇l͇i͇n͇e͇, D̤o̤t̤t̤e̤d̤ ̤l̤i̤n̤e̤, w̤a̤v̤e̤ ̤l̤i̤n̤e̤ Live online! paste on WhatsApp, Facebook, Instagram, Twitter, we have several tools to make your life easier! Access!",
  todosCamposObrigatorios: "All fields are required",
  avisoNovidade: "Try it out with",
  avisoNovidadeBold: "dark mode!, ",
  avisoNovidade2: "soon new tools will be available.",
  ferramentasPopulares: "Popular tools",
  ferramentasPopularesDescricao: "Tools that are most accessed by users.",
  formatadoresCodigoPopularCat: "Formatters",
  formatadoresCodigoPopular: "Code Formatter",
  geradorLorenPopular: "Loren Ipsum Generator",
  avisoManificarCodigo: "It will soon be possible to",
  avisoManificarCodigoBold: "minify",
  avisoManificarCodigo2: "your code!",
  descricaoConversorTextoHomePopular:
    "Great tool for those who wrote everything in capital letters or need to format it in a specific way.",
  descricaoFormatadorCodigoHomePopular:
    "Make your code more organized, with support for several languages such as HTML, CSS, Javascript, Vue, XML, PHP, JSON, YAML, MarkDown.",
  descricaoGeradorLorenHomePopular:
    "Generate text for your page, mockups, among others. Great tool for anyone who wants to create a sentence or paragraph.",
  descricaoFormatadorCodigoBannerHomePopular:
    "Formatter with elegant design, easy to use, was made especially for devs. With support for several languages, no more changing sites for each language you want to format.",
  linguagemEspecifica:
    "Do you need any specific language? Tell us in the chat that we will do it as soon as possible.",
  TituloSite: "All Facilitie",
  paletaCores: "Online Color Palette",
  paletaCoresDescricao:
    "List of nice colors with their codes to use in your project",
  paletaCoresDescricaoSeo:
    "Color palette to use in projects, web design, photoshop, illustrator, programming, website, online, nice colors.",
  vermelho: "Red",
  rosa: "Pink",
  roxo: "Purple",
  roxoEscuro: "Dark purple",
  anil: "Indigo",
  azul: "Blue",
  azulClaro: "Light Blue",
  ciano: "Cyan",
  verdeAzulado: "Teal",
  verde: "Green",
  verdeClaro: "Light Green",
  lima: "Lime",
  amarelo: "Yellow",
  ambar: "Amber",
  laranja: "Orange",
  laranjaEscuro: "Dark Orange",
  marrom: "Brown",
  azulAcidentado: "Blue Grey",
  cinza: "Grey",
  colorPickerDescricaoSEO:
    "Capture all the colors of an image, showing them in RGB, HSL AND HEX, with built-in color picker! Access!",
  colorPickerDescricao:
    "Capture all colors in an image, showing in RGB, HSL AND HEX.",
  alternarModo: "To switch between codes, click",
  colorPickerDescricao2: "RGBA, HSLA and HEX are supported.",
  capturearCorImagem: "Capture colors from an image",
  capturearCorImagemDescricao:
    "Upload your image and it will magically show the colors of your photo :)",
  alterarFoto: "Change",
  removerFoto: "Remove",
  tipPassarPicker: "Switch to Color Picker",
  arrastarImagem: "Drag an image or click here",
  gerandoCores: "Generating colors",
  ferramentasNovas: "New Tools",
  ferramentasNovasDescricao: "Tools that just came out of the oven :)",
  paletaCoresHome: "Color palette",
  paletaCoresHomeDescricao:
    "Color Palette with its respective codes, ready to be copied, Great tool for designers.",
  colorPickerDescricaoHome:
    "Capture the colors of a photo with the codes of each color, with color picker together, Great tool for designers.",
  obrigadoContato: "Thanks for the message, we will reply soon!",
  termosUso: "Terms of use",
  termosUsoTexto:
    "When accessing All Facilities, you must be aware and in accordance with the established terms. Otherwise, please do not use our tools.",
  termosUsoTexto2:
    "All Facilities reserves the right to change the terms of use at any time.",
  licencaUso: "Use license",
  licencaUsoTexto:
    "All Facilities ensures limited access only to those who agree and comply with the terms of use.",
  licencaUsoTexto2:
    "The All Facilities reserves the right to limit or ban access to anyone if there is a",
  licencaUsoTexto3: "violation",
  licencaUsoTexto4: "of the terms of use.",
  geradorFoto: "Online Photo generator",
  geradorFotoDesc: "Generate a photo of any size, with options to customize",
  texto: "Text",
  tamanho: "Size",
  corTexto: "Text color",
  formato: "Format",
  geradorFotoHome: "Photo generator",
  geradorFotoDescHome:
    "With this tool you can generate photos dynamically, with any size, color and with text in the middle",
  geradorFotoDescSEO:
    "Generate dynamic photos to use in your projects, we have more than 30 tools! Access!",
  sorteadorNumero: "Number Drawer",
  sorteadorNumeroOnline: "Online Number Drawer",
  sorteadorNumeroOnlineDesc: "Draw random numbers with options",
  sortear: "draw",
  minimo: "Minimum",
  maximo: "Maximum",
  numeroMinMaiorMax: "The Minimum number cannot be greater than the Maximum",
  quantidadeMenorMax: "The Quantity must be less than the Maximum",
  sorteadorSEOTitulo: "Online Number Drawer",
  sorteadorSEODesc:
    "Draw random numbers with quantity option, We have more than 30 tools! Access!",
  sorteadores: "Sorters",
  pesquisarFerramenta: "Search Tools",
  resultado: "Result",
  resultadoNEncontrado: "We didn't find what you searching for :(",
  geradorFotos: "Image Generator",
  descricaoContatoSEO:
    "We have several tools like color picker, image color capture, image generator, and much more! contact us",
};
